# NUMPY

In [1]:
import numpy as np

In [28]:
a=[1,2,3,4]#list
b=(3,4,5)#tuple
c=('a','b','c')#string tuple
print(np.array(a))
print(np.array(b))
print(np.array(c))


[1 2 3 4]
[3 4 5]
['a' 'b' 'c']


In [29]:
c=np.linspace(1,10,10)#we will get 10 values between 1 to 100 it divides values equally(start,end,no.of values needed)
print(c)
np.info(c)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x232f354d070
byteorder:  little
byteswap:  False
type: float64


In [32]:
c=np.arange(1,10,10)#it will have fixed step size(start,end,step)
print(c)
np.info(c)

[1]
class:  ndarray
shape:  (1,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x232f387da50
byteorder:  little
byteswap:  False
type: int32


In [36]:
d=np.zeros((3,3,4))#3-dimensional
k=np.ones(3)#1-d
l=np.ones((2,3))#2-d
print(d)
print(k)
print(l)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [70]:
k=np.array([[2,2,8],[4,5,6]])#2-D
p=np.array(8)#0-d scalar
print(p)
t=np.array([1,3,4,5])#1-d
print(t)

print(k.dtype)#data type of array
print(k.itemsize)#size of integer
print(np.copy(k))#copy of array
print(np.ndim(k))#dimension
print(np.shape(k))##(rows,columns)
print(np.size(k))
print(type(k))
print(k)

8
[1 3 4 5]
int32
4
[[200   2   8]
 [  4   5   6]]
2
(2, 3)
6
<class 'numpy.ndarray'>
[[200   2   8]
 [  4   5   6]]


In [86]:
k=np.array([[2,2,8],[4,5,6]])
p=np.array(8)#1d*2d
print(np.multiply(k,p))
t=np.array([[9,5,8],[8,5,6]])
print(np.multiply(k,t))#2d*2d




[[16 16 64]
 [32 40 48]]
[[18 10 64]
 [32 25 36]]
6


# Slicing

In [83]:
t=np.array([1,3,4,5])#1-d
print(t[1:])
print(t[:3])
print(t[::3])#t[start:end:step] here start =0 end =length of array,step=3 for every 3rd element is printed

[3 4 5]
[1 3 4]
[1 5]


In [85]:
print(t[1])#indexing
print(t[-1])


3
5


In [89]:
k=np.array([[9,5,8],[8,5,6]])
k[1][2]


6

In [90]:
k=np.array([[-9,-5,0],[8,-5,6]])
t=np.where(k<0,"neg","pos")#if condition statifies then neg else pos
print(t)

[['neg' 'neg' 'pos']
 ['pos' 'neg' 'pos']]


In [96]:
v=np.array([[1.23,2,3.68],[5,8.999,3.89]])
print(np.around(v))
print(np.around(v,decimals =1))
print(np.around(v,decimals =-1))#if negative then it round up the value left to decimal
print(np.floor(v))#rounds to smallest
print(np.ceil(v))#rounds to next largest if it is decimal

[[1. 2. 4.]
 [5. 9. 4.]]
[[1.2 2.  3.7]
 [5.  9.  3.9]]
[[ 0.  0.  0.]
 [ 0. 10.  0.]]
[[1. 2. 3.]
 [5. 8. 3.]]
[[2. 2. 4.]
 [5. 9. 4.]]


In [105]:
k=np.array([[9,5,0],[8,5,6]])
print(np.sum(k))
print(np.sum(k,axis=0))#add of rows
print(np.sum(k,axis=1))#add of columns
print(np.sum(k,axis=-1))#add from last to first

33
[17 10  6]
[14 19]
[14 19]


In [109]:
print(np.mean(k))

print(np.mean(k,axis=0))
print(np.mean(k,axis=1))

print(np.median(k))
print(np.median(k,axis=0))
print(np.median(k,axis=1))


print(np.std(k))
print(np.std(k,axis=0))
print(np.std(k,axis=1))

5.5
[8.5 5.  3. ]
[4.66666667 6.33333333]
5.5
[8.5 5.  3. ]
[5. 6.]
2.8722813232690143
[0.5 0.  3. ]
[3.68178701 1.24721913]
